### ISSUE TITLE
Example section in Markdown: every line of code should have indentation

### ISSUE THREAD

**Issue by dermeister0** [ChaseFlorell/psDoc#9]
```
    $(FixString($_.code | out-string ))
```

The code makes indentation for the first line only. All other example text is broken.

**Comment by ChaseFlorell** [comment]
Do you have a PR you'd like to submit? I'll happily pull in whatever you've got.

**Comment by codepersononline** [comment]
Guys I don't think this one is straight forward to do if you want to keep a separation of concerns between your PSM1 code and html/bootstrap.

My understanding of the code is that when your custom module is first loaded with the import-module cmdlet, it reads the .example section, and then converts the code portion of it into a SINGLE NoteProperty object (which can be accessed by get-command -modulename blah).
in other words, if an .EXAMPLE section included say a 5 line script. you would need to write it all on a single line separated by ';' statements for it to work correctly.

Otherwise, your .EXAMPLE section would need to contain HTML formatting elements 
to tell the browser how to render the powershell code.  Because, when powershell auto populates the $_.code property for the example, if will truncate early (on the first carriage return). 

that being said, It might be possible to find a workaround , by using a delimiter of some kind.

**Comment by dermeister0** [comment]
I have investigated how the .EXAMPLE section works. @strathbone is right, only one line of code is supported.

Here is a code of the parser:
https://github.com/PowerShell/PowerShell/blob/309bf603f9aff9009dce7e725d42b2d4f99f58c9/src/System.Management.Automation/help/HelpCommentsParser.cs#L480

I will close the issue, because it's not correct.
